apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik
  namespace: prod
  annotations:
    # This tells cert-manager to automatically issue certificates for this Gateway
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  gatewayClassName: traefik
  listeners:
    - name: https-traefik
      hostname: local.traefik.com
      protocol: HTTPS
      port: 8443
      tls:
        mode: Terminate
        certificateRefs:
          - name: traefik-tls-cert  # cert-manager will create a secret with this name
            group: ""               # Empty string means standard core Kubernetes API Group (Secret)
            kind: Secret
            
    - name: https-grafana
      hostname: local.grafana.com
      protocol: HTTPS
      port: 8443
      tls: 
        mode: Terminate
        certificateRefs:
          - name: grafana-tls-cert  # cert-manager will create a secret with this name
            group: ""
            kind: Secret